blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
# direct import of view, since di na gumawa ng urls.py sa users?????
from users import views as user_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('', include('blogs.urls')),
]

blogs/urls.py
from django.urls import path
from . import views
app_name = "blogs"

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about')
]

blogs/models.py
from django.contrib.auth.models import User
# https://www.youtube.com/watch?v=aHC3uTkT9r8
from django.utils import timezone
from django.db import models
from django.db.models.fields import CharField


# pip install django-autoslug
from autoslug import AutoSlugField

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title', unique=True, always_update=False)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now) 
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    #post model and user model will have a relationship, since user will author a post
    #use a FK

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
# Create your views here.


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blogs/home.html', context)


def about(request):
    return render(request, 'blogs/about.html', {})

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def register(request):
    #create an instance
    form = UserCreationForm()
    return render(request, 'users/register.html', {'FORMvariableTHIS': form})

templates/_base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blogster</title>
    <link rel="stylesheet" href="{% static 'bulma.min.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
      crossorigin="anonymous"
    />
    <!-- <link rel="stylesheet" href="{% static 'debug.css' %}" /> -->
  </head>
  <body class="base">
    <!-- navbar -->
    {% include '_navbar.html' %}
    <!-- container -->
    <div class="section">
      <div class="container">
        <div class="columns">
          <div class="column is-8">
            {% block content %}{% endblock content %}
          </div>
          <div class="column is-4">
            <aside class="menu">
              <p class="menu-label is-italic">
                <strong>Side Menu</strong>
              </p>
              <ul class="menu-list">
                <li><a>Latest Post</a></li>
                <li><a>Announcement</a></li>
                <li><a>Calendars</a></li>
                <li><a>etc</a></li>
              </ul>
            </aside>
          </div>
        </div>
      </div>
    </div>
    <!-- end container -->
  </body>
  <script src="{% static 'main.js' %}"></script>
</html>

templates/_navbar.html
{% load static %}
<nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="https://bulma.io">
        <img src="{% static 'logopng.png' %}" />
      </a>

      <a
        role="button"
        class="navbar-burger"
        aria-label="menu"
        aria-expanded="false"
        data-target="navbarBasic"
      >
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasic" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="{% url 'blogs:home' %}"> Home </a>

        <a class="navbar-item" href="{% url 'blogs:about' %}"> About </a>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <a class="button is-light"> Register </a>
            <a class="button is-primary">
              <strong>Log in</strong>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

templates/blogs/about.html
{% extends '_base.html' %}
{% block content %}
    <h1>about</h1>
{% endblock content %}

templates/blogs/home.html
{% extends '_base.html' %} 

{% block content %} 

{% for post in posts %}

<!-- start -->
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <img src="https://bulma.io/images/placeholders/128x128.png" />
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong>{{post.author}}</strong> <br />
        <small>{{post.date_posted |date:"F d, Y" }}</small>
        <h1 class="title is-size-6">{{post.title}}</h1>
        {{post.content}}
      </p>
    </div>
    <nav class="level is-mobile">
      <div class="level-left">
        <a class="level-item">
          <span class="icon is-small"><i class="fas fa-reply"></i></span>
        </a>
        <a class="level-item">
          <span class="icon is-small"><i class="fas fa-retweet"></i></span>
        </a>
        <a class="level-item">
          <span class="icon is-small"><i class="fas fa-heart"></i></span>
        </a>
      </div>
    </nav>
  </div>
  <div class="media-right">
    <button class="delete"></button>
  </div>
</article>

{% endfor %} 

{% endblock content %}

templates/users/register.html
{% extends '_base.html' %} {% block content %}
<!-- pip install django-crispy-forms -->
<!-- action is where to send the DATA -->
<!-- method  -->
<div class="container">
  <form action="" method="POST">
    {% csrf_token %}
    <div class="field">
        <label class="label">TO FIX THE FUCKING FORM</label>
        {{FORMvariableTHIS.as_p}}
        <hr>
      <label class="label">Username</label>
      <div class="control has-icons-left has-icons-right">
        <input class="input" type="text" placeholder="Enter your username" />
        <span class="icon is-small is-left">
          <i class="fas fa-user"></i>
        </span>
        <!-- <span class="icon is-small is-right">
            <i class="fas fa-check"></i>
          </span> -->
      </div>
      <!-- <p class="help is-success">This username is available</p> -->
    </div>
    <label class="label">Password</label>
    <div class="control has-icons-left has-icons-right">
      <input class="input" type="text" placeholder="Enter a unique password" />
      <span class="icon is-small is-left">
        <i class="fas fa-key"></i>
      </span>
    </div>
  </form>
</div>
{% endblock content %}